import { epoch, places, type WorldEvent, type PlaceId } from "./model.js";
function event(
  scenario: string,
  index: number,
  type: WorldEvent["type"],
  place: PlaceId,
  payload: WorldEvent["payload"],
  source: WorldEvent["source"]["id"],
): WorldEvent {
  return {
    id: `${scenario}:${index}`,
    timestamp: new Date(Date.parse(epoch) + index * 60_000).toISOString(),
    type,
    place,
    payload,
    source: { id: source, label: source.replace("replay-", "Scenario / ") },
    scopes: [
      places[place].scope,
      places[place].region,
      ...(scenario === "energy"
        ? (["domain:energy", "domain:aviation"] as const)
        : []),
    ],
  } as WorldEvent;
}
export const scenarios = {
  weather: {
    title: "Japan / weather escalation",
    subtitle: "Weather → transport → Japan → Asia → Global",
    events: [
      event(
        "weather",
        1,
        "weather_warning",
        "jp",
        { warning: 2, windKph: 65, rainMm: 90 },
        "replay-weather",
      ),
      event(
        "weather",
        2,
        "weather_warning",
        "jp",
        { warning: 4, windKph: 135, rainMm: 240 },
        "replay-weather",
      ),
      event(
        "weather",
        3,
        "transport_disruption",
        "jp",
        { cancelled: 47, delayed: 83 },
        "replay-aviation",
      ),
      event(
        "weather",
        4,
        "transport_disruption",
        "jp",
        { railWarnings: 3 },
        "replay-rail",
      ),
      event(
        "weather",
        5,
        "weather_warning",
        "jp",
        { warning: 5, windKph: 170, rainMm: 320 },
        "replay-weather",
      ),
      event(
        "weather",
        6,
        "weather_warning",
        "jp",
        { warning: 1, windKph: 35, rainMm: 30 },
        "replay-weather",
      ),
      event(
        "weather",
        7,
        "transport_disruption",
        "jp",
        { cancelled: 8, delayed: 18, railWarnings: 1 },
        "replay-aviation",
      ),
      event(
        "weather",
        8,
        "weather_warning",
        "jp",
        { warning: 0, windKph: 12, rainMm: 0 },
        "replay-weather",
      ),
      event(
        "weather",
        9,
        "transport_disruption",
        "jp",
        { cancelled: 0, delayed: 0, railWarnings: 0 },
        "replay-rail",
      ),
    ],
  },
  energy: {
    title: "Energy / supply shock",
    subtitle: "Supply → energy → imports / aviation / Europe",
    events: [
      event(
        "energy",
        1,
        "infrastructure_incident",
        "me",
        { supplyOfflinePct: 35, infrastructureOutages: 2 },
        "replay-wire",
      ),
      event(
        "energy",
        2,
        "market_move",
        "me",
        { oilChangePct: 12, volatility: 34 },
        "replay-market",
      ),
      event(
        "energy",
        3,
        "transport_disruption",
        "me",
        { shippingDelayHours: 36 },
        "replay-shipping",
      ),
      event(
        "energy",
        4,
        "transport_disruption",
        "jp",
        { fuelSurchargePct: 18 },
        "replay-aviation",
      ),
      event(
        "energy",
        5,
        "major_news",
        "me",
        { supplyOfflinePct: 8, infrastructureOutages: 0, notice: "restored" },
        "replay-wire",
      ),
    ],
  },
  markets: {
    title: "US → the world / market ripple",
    subtitle: "US event → shared pressure → Japan & Europe → world attention",
    events: [
      event(
        "markets",
        1,
        "market_move",
        "us",
        { changePct: -4.2, volatility: 28 },
        "replay-market",
      ),
      event(
        "markets",
        2,
        "market_move",
        "us",
        { changePct: -5.1, volatility: 36 },
        "replay-market",
      ),
      event(
        "markets",
        3,
        "market_move",
        "us",
        { changePct: -6.8, volatility: 48 },
        "replay-market",
      ),
      event(
        "markets",
        4,
        "government_notice",
        "us",
        { notice: "support_announced" },
        "replay-wire",
      ),
      event(
        "markets",
        5,
        "market_move",
        "us",
        { changePct: -1.2, volatility: 19 },
        "replay-market",
      ),
      event(
        "markets",
        6,
        "market_move",
        "us",
        { changePct: -0.4, volatility: 16 },
        "replay-market",
      ),
    ],
  },
} as const;
export type ScenarioId = keyof typeof scenarios;
